name: Check Update

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule' || (github.event_name == 'schedule' && github.repository == 'ronsonm/factorio-docker')

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Run update script
        run: ./update.sh
        shell: bash
